pymilvus_orm/index.py
pymilvus_orm/partition.py
tests/test_index.py
tests/test_partition.py
tests/utils.py

Update index and partition unittests

---

tests/mock_milvus.py

Implement mock milvus

---

tests/mock_milvus.py
tests/test_collection.py
tests/test_partition.py

Add partition impl in MockMilvus

---

pymilvus_orm/partition.py
pymilvus_orm/prepare.py
tests/test_index.py
tests/test_partition.py
tests/utils.py

Fix some partition unittests

---

.github/workflows/integration.yml
.github/workflows/pull_request.yml
.gitignore
Makefile

Update GitHub Actions

---

README.md

Add codecov badge in README.md

---

Makefile
examples/example.py
pymilvus_orm/collection.py
pymilvus_orm/connections.py

Add an example

---

pymilvus_orm/collection.py

Delete auto_id param for collection schema

---

examples/collection.py
pymilvus_orm/index.py

Add test for create index

---

pymilvus_orm/collection.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
tests/test_index.py
tests/test_partition.py

Add check in some interfaces

---

.github/workflows/integration.yml
Makefile
pymilvus_orm/partition.py
tests/mock_milvus.py
tests/test_collection.py
tests/test_connections.py
tests/test_index.py
tests/test_partition.py
tests/test_schema.py

Update tests in test_partition

---

examples/collection.py
requirements.txt

Add create index test for binary data

---

examples/collection.py
pymilvus_orm/collection.py
pymilvus_orm/prepare.py

Fix bug for inserting when collection schema has a primary field

---

pymilvus_orm/collection.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
pymilvus_orm/schema.py
pymilvus_orm/search.py
pymilvus_orm/utility.py
tests/test_utility.py

Add TODO marks

---

pymilvus_orm/collection.py
pymilvus_orm/index.py
pymilvus_orm/partition.py

Fix mistake return type

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py
pymilvus_orm/utility.py

Update todo items

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py
tests/utils.py

Fix todo lists

---

docs/source/api/collection.rst
docs/source/index.rst
pymilvus_orm/collection.py

Referencing other interfaces in interface comments

---

examples/collection.py
pymilvus_orm/schema.py

Add case when CollectionSchema specifies the primary field

---

examples/connections.py

Test trigger readocs

---

docs/source/api/collection.rst
pymilvus_orm/collection.py

Add interface documentation about collection

---

Makefile
examples/example.py
examples/example_index.py
pymilvus_orm/collection.py
pymilvus_orm/partition.py
tests/mock_milvus.py
tests/test_collection.py
tests/test_index.py
tests/utils.py

Add index related examples

---

examples/hello_pymilvus_orm.py
pymilvus_orm/__init__.py
setup.py

Add requirements for installing and add hello_milvus

---

pymilvus_orm/__init__.py
pymilvus_orm/collection.py
requirements.txt

Implement and add example to Collection.search

---

pymilvus_orm/exceptions.py

Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

Add exceptions and errors class

---

pymilvus_orm/collection.py

Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

Add exceptions and errors in collection

---

pymilvus_orm/connections.py

Improve the docstring of connections.Connections

---

pymilvus_orm/partition.py

Signed-off-by: sunby <bingyi.sun@zilliz.com>

Move return type behind the return annotation in partition.py

---

pymilvus_orm/index.py

Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

update return format in index.py

---

examples/example_index.py

Add dim param example

---

pymilvus_orm/index.py

Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

add example for index.py

---

pymilvus_orm/partition.py

Signed-off-by: sunby <bingyi.sun@zilliz.com>

Add examples in partition.py

---

docs/source/api/collection.rst

Improve interface documentation

---

docs/source/results.rst

Add demo example to explain how to deal with search result

---

pymilvus_orm/__init__.py
pymilvus_orm/collection.py
pymilvus_orm/connections.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
pymilvus_orm/schema.py
pymilvus_orm/utility.py
tests/conftest.py
tests/test_connections.py
tests/test_partition.py
tests/utils.py

Fix circular reference

---

pymilvus_orm/collection.py
pymilvus_orm/index.py
pymilvus_orm/utility.py
tests/mock_milvus.py

Signed-off-by: godchen <qingxiang.chen@zilliz.com>

Add utility doc

---

pymilvus_orm/collection.py

Improve comment for collection

---

pymilvus_orm/index.py

Signed-off-by: sunby <bingyi.sun@zilliz.com>

Fix examples in index.py

---

docs/source/tutorial.rst

Add a tutorial about how to use pymilvus-orm

---

pymilvus_orm/partition.py

Fix example/partition.py

---

docs/source/api/collection.rst
docs/source/api/index.rst
docs/source/api/partition.rst

Add descriptions of collection, partiton and index

---

pymilvus_orm/collection.py

Add example for partition and index in collection

---

pymilvus_orm/collection.py
pymilvus_orm/exceptions.py
pymilvus_orm/schema.py
pymilvus_orm/types.py
tests/test_schema.py
tests/test_types.py

Add logic of parse fields from pandas dataframe

---

pymilvus_orm/collection.py
pymilvus_orm/prepare.py
pymilvus_orm/schema.py
tests/test_collection.py
tests/utils.py

Add check for collection about pandas.DataFrame

---

pymilvus_orm/collection.py
tests/utils.py

Improve example and unittest

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py
pymilvus_orm/prepare.py

Fix bug for insert data about pandas.DataFrame

---

pymilvus_orm/partition.py

Add search implementation in Partition

---

pymilvus_orm/collection.py

Fix bug with raising exception

---

pymilvus_orm/partition.py
requirements.txt
tests/mock_milvus.py
tests/test_partition.py

Implement the num_entities of partition by get_partition_stats

---

.github/workflows/lint.yml
Makefile
pymilvus_orm/__init__.py
pymilvus_orm/collection.py
pymilvus_orm/connections.py
pymilvus_orm/constants.py
pymilvus_orm/default_config.py
pymilvus_orm/exceptions.py
pymilvus_orm/future.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
pymilvus_orm/prepare.py
pymilvus_orm/schema.py
pymilvus_orm/search.py
pymilvus_orm/types.py
pymilvus_orm/utility.py
requirements.txt

Add pylint check to github action

---

pymilvus_orm/connections.py

Fix bug for connection get_connection

---

pymilvus_orm/connections.py
tests/test_connections.py

Change some function logic of Connections

---

pymilvus_orm/schema.py
pymilvus_orm/types.py

Fix bug for checking data

---

pymilvus_orm/prepare.py
pymilvus_orm/schema.py

Fix bug for creating a collection with two primary field

---

pymilvus_orm/connections.py

Create connection when configure connection

---

requirements.txt

Change dependency to pymilvus

---

setup.py

Fix bug: add dependency_links to setup.py

---

examples/collection.py
examples/hello_milvus.py
pymilvus_orm/types.py
setup.py
tests/test_types.py

Fix bug: infer binary_vector failed

---

pymilvus_orm/connections.py

Implement connections class by single instance

---

.github/workflows/package.yml

Fix bug: rename master to main

---

.github/workflows/package.yml

Fix bug: actions should use master branch

---

pymilvus_orm/exceptions.py
pymilvus_orm/schema.py

The type of the data inserted into the collection must be like list

---

pymilvus_orm/collection.py
pymilvus_orm/schema.py

Check schema when creating collection

---

pymilvus_orm/collection.py

Support multi vector fields

---

pymilvus_orm/schema.py

Check field type of schema

---

pymilvus_orm/collection.py
pymilvus_orm/schema.py

Throw exception when the data in the same column is not the same type

---

docs/source/install.rst
pymilvus_orm/connections.py
requirements.txt
tests/conftest.py
tests/mock_milvus.py
tests/test_connections.py

Update pymilvus version

---

setup.py

Upgrade pymilvus

---

pymilvus_orm/prepare.py

Currently does not support numpy.ndarray.

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py

Fix bug of insert

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py
pymilvus_orm/prepare.py

Fix bug for insert

---

pylint.conf
pymilvus_orm/collection.py
pymilvus_orm/exceptions.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
pymilvus_orm/utility.py

Throw exception of create instance while collection is None

---

pymilvus_orm/collection.py
pymilvus_orm/index.py

Remove field_name for collection.indexes

---

pymilvus_orm/__init__.py
pymilvus_orm/collection.py
pymilvus_orm/connections.py
pymilvus_orm/constants.py
pymilvus_orm/default_config.py
pymilvus_orm/exceptions.py
pymilvus_orm/future.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
pymilvus_orm/prepare.py
pymilvus_orm/schema.py
pymilvus_orm/search.py
pymilvus_orm/types.py
pymilvus_orm/utility.py

Minor editorial updates

---

pymilvus_orm/collection.py
pymilvus_orm/connections.py
tests/test_connections.py

Change Connections to thread-safe singleton class

---

pylint.conf
pymilvus_orm/collection.py
pymilvus_orm/connections.py
pymilvus_orm/index.py
pymilvus_orm/partition.py
tests/test_collection.py
tests/test_index.py

Delete unused arguments

---

examples/example.py
pymilvus_orm/collection.py
requirements.txt

Rename expression to expr

---

docs/source/tutorial.rst

Correct code in docs

---

setup.py

Update requirement pymilvus version

---

examples/collection.py
examples/connections.py
examples/example_index.py
examples/hello_milvus.py
examples/partition.py
pymilvus_orm/collection.py
pymilvus_orm/partition.py

Checkout example
Signed-off-by: godchen <qingxiang.chen@zilliz.com>

Checkout example

---

pymilvus_orm/schema.py

Add deepcopy for FieldSchema

---

pymilvus_orm/schema.py

Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

fix binary vector dim

---

requirements.txt

synchronize the latest pymilvus version

---

examples/example.py

Remove unused print

---

pymilvus_orm/index.py

See also [Milvus repo issue #5408](https://github.com/milvus-io/milvus/issues/5408)
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

Add to_dict & __eq__ for Index Class

---

examples/example.py
examples/example_index.py
pymilvus_orm/partition.py
pymilvus_orm/schema.py
requirements.txt
setup.py

Check params for schema

---

OWNERS

Add scsven into approvers

---

pymilvus_orm/schema.py

Fix bug for auto_id in CollectionSchema

---

examples/collection.py
pymilvus_orm/collection.py
pymilvus_orm/prepare.py
tests/test_collection.py

Fix bug for constructing from dataframe

---

requirements.txt
setup.py

Update the version of pymilvus

---

.github/mergify.yml

Remove readthedocs as ci-passed requirements

---

pymilvus_orm/connections.py

See also: https://github.com/milvus-io/milvus/issues/5725

Add checks for alias

---

pymilvus_orm/connections.py
pymilvus_orm/utility.py

See alse: https://github.com/milvus-io/milvus/issues/5725

Fix alias check bug

---

pymilvus_orm/schema.py

Fix bug for two primary fields

---

pymilvus_orm/connections.py

Signed-off-by: wangting0128 <ting.wang@zilliz.com>

Update exception messages of connection interface

---

pymilvus_orm/collection.py
pymilvus_orm/exceptions.py

Solves: [milvus-io/milvus#6044](https://github.com/milvus-io/milvus/issues/6044)
Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

Add expr type check

---

.github/workflows/publish_dev_package.yml
.github/workflows/publish_release_package.yml

Update publish GitHub Actions

---

requirements.txt
setup.py

Update dependent pymilvus version

---

README.md

Fix PyMilvus-ORM readme

---

docs/source/api/connections.rst
docs/source/api/future.rst
pymilvus_orm/collection.py
pymilvus_orm/connections.py

Optimize import statement in comments

---

pymilvus_orm/utility.py

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

Fix utility.py example

---

pymilvus_orm/index.py

Update test case of index in docs

---

pymilvus_orm/schema.py

Update test case in docs

---

CHANGELOG.md
examples/hello_milvus.py
pymilvus_orm/search.py

[+] Add entity function to Hit object
[+] Add usage in the example
[+] Add changes to CHANGELOG

Get value of metadata fields from search result output

---

examples/hello_milvus.py

Collection has no parameter of data

---

examples/hello_milvus.py

Tidy example.py

---

docs/source/res/Intro_to_Indexes.md

Fix Intro_to_Indexes.md

---

docs/source/contribute.rst
docs/source/install.rst
docs/source/tutorial.rst

Update documentation for pymilvus-orm

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py

Add repr function for collection

---

pymilvus_orm/collection.py

Fix bug for misspell

---

pymilvus_orm/search.py
tests/mock_milvus.py
tests/mock_result.py
tests/test_collection.py

Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

Support human readable mutation result

---

README.md

Add slack channel into readme

---

.github/workflows/release_event.yml
.github/workflows/update_branch_doc_event.yml

- Update remote repo name from `milvus-io/docs` to `milvus-io/web-content`.
- Add new action `update_branch_doc_event.yml` to handle: Update milvus official website's docs when corresponding branch update files under pymilvus-orm `docs`.

update action for docs(latest name is web-content)

---

docs/source/tutorial.rst

Fix tutorial docs

---

docs/source/tutorial.rst

Signed-off-by: yanliang567 <yanliang.qiao@zilliz.com>

update code sample

---

docs/source/tutorial.rst

Signed-off-by: yanliang567 <yanliang.qiao@zilliz.com>

Add note for inserting sample

---

docs/source/tutorial.rst

Fix doc link bug

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py

Construct partition without check

---

setup.py

Signed-off-by: yanliang567 <yanliang.qiao@zilliz.com>

update orm version

---

README.md
docs/source/install.rst
requirements.txt
setup.py

Prepare for the release of version 2.0.0rc2

---

setup.py

Fixbug: Add dependency link to pypi.org

---

examples/example.py
pymilvus_orm/constants.py
pymilvus_orm/exceptions.py
pymilvus_orm/utility.py

Signed-off-by: yhmo <yihua.mo@zilliz.com>

refine result of calc_distance()

---

examples/example.py
examples/example_index.py
pymilvus_orm/schema.py
pymilvus_orm/utility.py

Fix small typo in documentation

---

pymilvus_orm/collection.py

fix issue: https://github.com/milvus-io/milvus/issues/6721

Unify the name of using

---

requirements.txt
setup.py

Update version of pymilvus

---

pymilvus_orm/utility.py
tests/mock_milvus.py

Fixbug: return bool instead of tuple

---

pymilvus_orm/collection.py
pymilvus_orm/index.py
pymilvus_orm/partition.py

issue: #267 
Signed-off-by: YunMei.Li <yunmei.li@zilliz.com>

Expose timeout parameter

---

requirements.txt
setup.py

Update pymilvus version, change logic of waiting for load

---

README.md

Add rc3 for README

---

pymilvus_orm/collection.py
pymilvus_orm/partition.py

Resolves: #274 
Signed-off-by: fishpenguin kun.yu@zilliz.com

Add query example doc

---

README.md

Change recommended version to 2.0.0rc4
